name: Ci/Cd Sac Catania

on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2

        
            - name: Zip time
              run: zip -r repo.zip . 

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: next-project
                path: repo.zip
            
            - name: Download Artifact 
              uses: actions/download-artifact@v4
              with:
                name: next-project


            - name: Commands on EC2
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.HOST }}
                username:  ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                port: ${{ secrets.SSH_PORT }}
                script: |
                    cd /home/ec2-user/
                    sudo rm -r next-app
                    rm repo.zip


            - name: Deploying to EC2
              uses: appleboy/scp-action@v0.1.7
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                port: ${{ secrets.PORT }}
                key: ${{ secrets.KEY }}
                source: /home/runner/work/next-repo/next-repo/repo.zip
                target: /home/ec2-user/
                strip_components: 2
            
            - name: Commands on EC2
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.HOST }}
                username:  ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                port: ${{ secrets.SSH_PORT }}
                script: |
                     cd /home/ec2-user/
                     unzip repo.zip -d /home/ec2-user/next-app 
                     cd next-app
                     npm install
                     pm2 start npm --name nextjs-app -- run start -- -p 3000
                     npx next build
                     npx next start
                     sudo systemctl restart nginx   


                
