name: Ci/Cd Sac Catania

on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2

        
            - name: Zip time
              run: zip -r repo.zip . 

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: next-project
                path: repo.zip
            
            - name: Download Artifact 
              uses: actions/download-artifact@v4
              with:
                name: next-project


            - name: Deploying to EC2
              uses: appleboy/scp-action@v0.1.7
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                port: ${{ secrets.PORT }}
                key: ${{ secrets.KEY }}
                source: /home/runner/work/next-repo/next-repo/repo.zip
                target: /home/ec2-user/
            
            - name: Commands on EC2
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: ${{ secrets.SSH_PORT }}
                script: |
                     cd /home/ec2-user/
                     echo "ciao" > helloworld.txt


                
